from typing import Optional, Protocol, Sequence

from src.domain.entities.demanda import Demanda
from src.domain.value_objects.status import StatusDemanda


class DemandaRepository(Protocol):
    def salvar(self, demanda: Demanda) -> Demanda: ...
    def buscar_por_id(self, id: int) -> Optional[Demanda]: ...
    def listar_por_status(self, status: StatusDemanda) -> Sequence[Demanda]: ...
    def listar_ativas(self) -> Sequence[Demanda]: ...
