from typing import Optional, Protocol, Sequence

from src.domain.entities.projeto_lei import ProjetoLei


class ProjetoLeiRepository(Protocol):
    def salvar(self, pl: ProjetoLei) -> ProjetoLei: ...
    def buscar_por_id(self, id: int) -> Optional[ProjetoLei]: ...
    def buscar_por_id_senado(self, id_senado: int) -> Optional[ProjetoLei]: ...
    def listar_por_demanda(self, demanda_id: int) -> Sequence[ProjetoLei]: ...
