# Generated by Django 5.0.6 on 2026-05-24 18:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DemandaModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('origem', models.CharField(max_length=50)),
                ('num_origem', models.IntegerField(blank=True, null=True)),
                ('texto', models.TextField()),
                ('dat_chegada', models.DateField()),
                ('dias_prazo', models.PositiveSmallIntegerField()),
                ('status', models.CharField(choices=[('PR', 'Pendente de Resposta'), ('PF', 'Pendente de Revisão'), ('PE', 'Pendente Externa'), ('C', 'Concluída')], default='PR', max_length=2)),
                ('dat_cadastro', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'callista_demanda',
                'ordering': ['-dat_chegada'],
            },
        ),
        migrations.CreateModel(
            name='FeriadoModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(unique=True)),
                ('nome', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'callista_feriado',
                'ordering': ['data'],
            },
        ),
        migrations.CreateModel(
            name='UsuarioModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('matricula', models.CharField(max_length=20, unique=True)),
                ('cargo', models.CharField(blank=True, default='', max_length=100)),
                ('is_ativo', models.BooleanField(default=True)),
                ('is_oculto', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Usuário',
                'verbose_name_plural': 'Usuários',
                'db_table': 'callista_usuario',
            },
        ),
        migrations.CreateModel(
            name='RespostaModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.TextField()),
                ('dat_resposta', models.DateTimeField(auto_now_add=True)),
                ('editado', models.BooleanField(default=False)),
                ('demanda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='respostas', to='django_orm.demandamodel')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='django_orm.usuariomodel')),
            ],
            options={
                'db_table': 'callista_resposta',
                'ordering': ['dat_resposta'],
            },
        ),
        migrations.AddField(
            model_name='demandamodel',
            name='relator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='demandas_como_relator', to='django_orm.usuariomodel'),
        ),
        migrations.AddField(
            model_name='demandamodel',
            name='revisor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='demandas_como_revisor', to='django_orm.usuariomodel'),
        ),
        migrations.CreateModel(
            name='AfastamentoModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dat_inicial', models.DateField()),
                ('dat_final', models.DateField()),
                ('motivo', models.CharField(max_length=200)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='afastamentos', to='django_orm.usuariomodel')),
            ],
            options={
                'db_table': 'callista_afastamento',
                'unique_together': {('usuario', 'dat_inicial', 'dat_final')},
            },
        ),
    ]
