# Generated by Django 5.0.6 on 2026-05-27 12:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_orm', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrigemDemandaModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sigla', models.CharField(max_length=10, unique=True)),
                ('nome', models.CharField(max_length=255)),
                ('prazo_padrao_dias', models.PositiveSmallIntegerField(default=5)),
                ('tem_numero', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Origem de Demanda',
                'verbose_name_plural': 'Origens de Demandas',
                'db_table': 'callista_origem_demanda',
            },
        ),
        migrations.AddField(
            model_name='demandamodel',
            name='criador',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='demandas_criadas', to='django_orm.usuariomodel'),
        ),
        migrations.AddField(
            model_name='demandamodel',
            name='dat_atribuicao_relator',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='demandamodel',
            name='dat_atribuicao_revisor',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='respostamodel',
            name='dat_edicao',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='respostamodel',
            name='editado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='respostas_editadas', to='django_orm.usuariomodel'),
        ),
        migrations.AlterField(
            model_name='respostamodel',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='respostas', to='django_orm.usuariomodel'),
        ),
        migrations.CreateModel(
            name='HistoricoAtribuicaoModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('RES', 'Resposta'), ('REV', 'Revisão')], max_length=3)),
                ('data_atribuicao', models.DateTimeField(auto_now_add=True)),
                ('valido', models.BooleanField(default=True)),
                ('demanda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historico_atribuicoes', to='django_orm.demandamodel')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='historico_atribuicoes', to='django_orm.usuariomodel')),
            ],
            options={
                'db_table': 'callista_historico_atrib',
                'ordering': ['data_atribuicao'],
            },
        ),
        migrations.AddField(
            model_name='demandamodel',
            name='origem_ref',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='demandas', to='django_orm.origemdemandamodel'),
        ),
        migrations.CreateModel(
            name='PendenciaExternaModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('justificativa', models.TextField()),
                ('data_inicio', models.DateTimeField(auto_now_add=True)),
                ('data_fim', models.DateTimeField(blank=True, null=True)),
                ('criador', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pendencias_criadas', to='django_orm.usuariomodel')),
                ('demanda', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='pendencia_externa', to='django_orm.demandamodel')),
            ],
            options={
                'db_table': 'callista_pendencia_externa',
            },
        ),
        migrations.CreateModel(
            name='RevisaoModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.TextField()),
                ('dat_revisao', models.DateTimeField(auto_now_add=True)),
                ('editado', models.BooleanField(default=False)),
                ('dat_edicao', models.DateTimeField(blank=True, null=True)),
                ('demanda', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='revisao', to='django_orm.demandamodel')),
                ('editado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='revisoes_editadas', to='django_orm.usuariomodel')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='revisoes', to='django_orm.usuariomodel')),
            ],
            options={
                'db_table': 'callista_revisao',
                'ordering': ['dat_revisao'],
            },
        ),
    ]
