# Generated by Django 5.0.6 on 2026-05-28 14:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_orm', '0002_schema_migracao_v2'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjetoLeiModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_senado', models.IntegerField(unique=True)),
                ('identificacao', models.CharField(max_length=50)),
                ('sigla', models.CharField(max_length=10)),
                ('numero', models.IntegerField()),
                ('ano', models.IntegerField()),
                ('ementa', models.TextField()),
                ('tramitando', models.BooleanField()),
                ('situacao_atual', models.CharField(max_length=200)),
                ('sigla_situacao', models.CharField(blank=True, max_length=20)),
                ('dat_situacao', models.DateField()),
                ('url_documento', models.CharField(blank=True, max_length=500)),
                ('autoria', models.CharField(blank=True, max_length=500)),
                ('dat_ultima_atualizacao', models.DateTimeField()),
                ('dat_snapshot', models.DateTimeField(auto_now=True)),
                ('demanda', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projetos_lei', to='django_orm.demandamodel')),
            ],
            options={
                'db_table': 'callista_projeto_lei',
                'ordering': ['-dat_ultima_atualizacao'],
            },
        ),
    ]
