# Generated by Django 6.0.5 on 2026-06-01 20:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_orm', '0003_adiciona_projeto_lei'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricoAtribuicaoModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('RES', 'Resposta'), ('REV', 'Revisão')], max_length=3)),
                ('data_atribuicao', models.DateTimeField(auto_now_add=True)),
                ('valido', models.BooleanField(default=True)),
                ('demanda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historico_atribuicoes', to='django_orm.demandamodel')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='historico_atribuicoes', to='django_orm.usuariomodel')),
            ],
            options={
                'db_table': 'callista_historico_atrib',
                'ordering': ['data_atribuicao'],
            },
        ),
        migrations.CreateModel(
            name='PendenciaExternaModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('justificativa', models.TextField()),
                ('data_inicio', models.DateTimeField(auto_now_add=True)),
                ('data_fim', models.DateTimeField(blank=True, null=True)),
                ('criador', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pendencias_criadas', to='django_orm.usuariomodel')),
                ('demanda', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='pendencia_externa', to='django_orm.demandamodel')),
            ],
            options={
                'db_table': 'callista_pendencia_externa',
            },
        ),
        migrations.CreateModel(
            name='RevisaoModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.TextField()),
                ('dat_revisao', models.DateTimeField(auto_now_add=True)),
                ('editado', models.BooleanField(default=False)),
                ('dat_edicao', models.DateTimeField(blank=True, null=True)),
                ('demanda', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='revisao', to='django_orm.demandamodel')),
                ('editado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='revisoes_editadas', to='django_orm.usuariomodel')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='revisoes', to='django_orm.usuariomodel')),
            ],
            options={
                'db_table': 'callista_revisao',
                'ordering': ['dat_revisao'],
            },
        ),
    ]
