# Generated by Django 6.0.5 on 2026-06-01 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_orm', '0004_historicoatribuicaomodel_pendenciaexternamodel_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrigemDemandaModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sigla', models.CharField(max_length=10, unique=True)),
                ('nome', models.CharField(max_length=100)),
                ('prazo_padrao_dias', models.PositiveSmallIntegerField()),
                ('tem_numero', models.BooleanField(default=False)),
                ('ativo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Origem de Demanda',
                'verbose_name_plural': 'Origens de Demanda',
                'db_table': 'callista_origem_demanda',
                'ordering': ['sigla'],
            },
        ),
        migrations.AlterModelOptions(
            name='afastamentomodel',
            options={'verbose_name': 'Afastamento', 'verbose_name_plural': 'Afastamentos'},
        ),
        migrations.AlterModelOptions(
            name='demandamodel',
            options={'ordering': ['-dat_chegada'], 'verbose_name': 'Demanda', 'verbose_name_plural': 'Demandas'},
        ),
        migrations.AlterModelOptions(
            name='feriadomodel',
            options={'ordering': ['data'], 'verbose_name': 'Feriado', 'verbose_name_plural': 'Feriados'},
        ),
    ]
